name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ github.sha }}-${{ github.run_number }}"
          name: "Release ${{ github.sha }}-${{ github.run_number }}"
          body: "Release notes for version ${{ github.sha }}-${{ github.run_number }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
