name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the project
      - name: Build project
        run: npm run build

      # Step 5: Create and push a version tag
      - name: Create GitHub tag
        run: |
          TAG_NAME="v0.${{ github.run_number }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      # Step 6: Publish to GitHub Releases
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v0.${{ github.run_number }}
          release_name: Release v0.${{ github.run_number }}
          assets: |
            build/index.html
