name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}-${{ github.sha.substring(0, 7) }}  
          name: "Release v${{ github.run_number }}-${{ github.sha.substring(0, 7) }}"
          body: "Release notes for version v${{ github.run_number }}-${{ github.sha.substring(0, 7) }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
